### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [KyleCRat/TC359_Project_Three#1]
It looks like the Heroku app linked to in the project showcase is hosting project 6, rather than project 3. Could you update the link for project 3? This makes it a lot easier for me to review. 

We will have to reuse Heroku app slots for many projects, since we only have 5 slots for unverified accounts, but we also need to make sure we don't replace projects *before* they've been reviewed.

Let me know if that explanation doesn't make sense. Otherwise, just reply here letting me know when you've updated the showcase.

**Comment by KyleCRat** [comment]
updated: Skill: Organize static assets in Sinatra. New app showing project 3. Project 6 still available at the old URL. Removed extra directory contents

**Comment by chrisvfritz** [comment]
:+1: Much better! Thanks.
